[build]
  base = "frontend"
  command = "npm run build:prod"
  publish = "dist"

[build.environment]
  VITE_DEV_MODE = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://che-prince-garba.onrender.com"