[build]
  command = "cd frontend && npm run build:prod"
  publish = "frontend/dist"

[build.environment]
  # Ces variables seront utilisées lors du build
  VITE_DEV_MODE = "false"

[context.production.environment]
  # Surcharge possible pour la prod (la variable VITE_API_URL sera définie dans Netlify UI)
  VITE_API_URL = "https://che-prince-garba.onrender.com"